name: Check Releases Workflow

on:
  workflow_dispatch:

jobs:
  check_releases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests

      - name: List releases
        id: list_releases
        run: |
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          OWNER="${{ github.repository_owner }}"
          REPO="${{ github.repository }}"
          URL="https://api.github.com/repos/$OWNER/$REPO/releases?per_page=100"
          releases=$(curl -sSL -H "Authorization: token $TOKEN" $URL)
          echo "::set-output name=releases::$releases"

      - name: Process releases
        id: process_releases
        run: |
          releases="${{ steps.list_releases.outputs.releases }}"
          filtered_releases=$(echo "$releases" | jq '.[] | select(.name | contains("beyond1lte") or contains("a40")) | select(.assets[].name | contains("recovery.img")) | select(.assets[].name | contains("recovery.tar") | not)')
          echo "::set-output name=filtered_releases::$filtered_releases"

      - name: Create recovery.tar
        id: create_tar
        run: |
          filtered_releases="${{ steps.process_releases.outputs.filtered_releases }}"
          for row in $(echo "${filtered_releases}" | jq -r '.[] | @base64'); do
            _jq() {
              echo ${row} | base64 --decode | jq -r ${1}
            }
            tag=$(_jq '.tag_name')
            asset_url=$(_jq '.assets[].url')
            asset_name=$(_jq '.assets[].name')
            download_url=$(curl -sSL -H "Authorization: token $TOKEN" $asset_url | jq -r '.browser_download_url')
            curl -sSL -O -J -H "Authorization: token $TOKEN" $download_url
            tar -cf recovery.tar recovery.img
            mv recovery.tar recovery-${tag}.tar
          done

      - name: Upload recovery.tar
        id: upload_tar
        uses: actions/upload-artifact@v2
        with:
          name: recovery.tar
          path: recovery-*.tar
